from modules.table_filling_cyk import is_accepted

def test_is_accepted():
    assert is_accepted("a") == True
    assert is_accepted("b") == False
    assert is_accepted("aa") == True
    assert is_accepted("ba") == True
    assert is_accepted("ab") == True
    assert is_accepted("bb") == False
    assert is_accepted("aaa") == True
    assert is_accepted("baa") == True
    assert is_accepted("aba") == True
    assert is_accepted("aab") == True
    assert is_accepted("bba") == True
    assert is_accepted("bab") == True
    assert is_accepted("abb") == True
    assert is_accepted("bbb") == False
    assert is_accepted("aaaa") == True
    assert is_accepted("baaa") == True
    assert is_accepted("abaa") == True
    assert is_accepted("aaba") == True
    assert is_accepted("aaab") == True
    assert is_accepted("bbaa") == True
    assert is_accepted("baba") == True
    assert is_accepted("baab") == True
    assert is_accepted("abba") == True
    assert is_accepted("abab") == True
    assert is_accepted("aabb") == True
    assert is_accepted("bbba") == True
    assert is_accepted("bbab") == True
    assert is_accepted("babb") == True
    assert is_accepted("abbb") == True
    assert is_accepted("bbbb") == False
    assert is_accepted("aaaaa") == True
    assert is_accepted("baaaa") == True
    assert is_accepted("abaaa") == True
    assert is_accepted("aabaa") == True
    assert is_accepted("aaaba") == True
    assert is_accepted("aaaab") == True
    assert is_accepted("bbaaa") == True
    assert is_accepted("babaa") == True
    assert is_accepted("baaba") == True
    assert is_accepted("baaab") == True
    assert is_accepted("abbaa") == True
    assert is_accepted("ababa") == True
    assert is_accepted("abaab") == True
    assert is_accepted("aabba") == True
    assert is_accepted("aabab") == True
    assert is_accepted("aaabb") == True
    assert is_accepted("bbbaa") == True
    assert is_accepted("bbaba") == True
    assert is_accepted("bbaab") == True
    assert is_accepted("babba") == True
    assert is_accepted("babab") == True
    assert is_accepted("baabb") == True
    assert is_accepted("abbba") == True
    assert is_accepted("abbab") == True
    assert is_accepted("ababb") == True
    assert is_accepted("aabbb") == True
    assert is_accepted("bbbba") == True
    assert is_accepted("bbbab") == True
    assert is_accepted("bbabb") == True
    assert is_accepted("babbb") == True
    assert is_accepted("abbbb") == True
    assert is_accepted("bbbbb") == False
    assert is_accepted("aaaaaa") == True
    assert is_accepted("baaaaa") == True
    assert is_accepted("abaaaa") == True
    assert is_accepted("aabaaa") == True
    assert is_accepted("aaabaa") == True
    assert is_accepted("aaaaba") == True
    assert is_accepted("aaaaab") == True
    assert is_accepted("bbaaaa") == True
    assert is_accepted("babaaa") == True
    assert is_accepted("baabaa") == True
    assert is_accepted("baaaba") == True
    assert is_accepted("baaaab") == True
    assert is_accepted("abbaaa") == True
    assert is_accepted("ababaa") == True
    assert is_accepted("abaaba") == True
    assert is_accepted("abaaab") == True
    assert is_accepted("aabbaa") == True
    assert is_accepted("aababa") == True
    assert is_accepted("aabaab") == True
    assert is_accepted("aaabba") == True
    assert is_accepted("aaabab") == True
    assert is_accepted("aaaabb") == True
    assert is_accepted("bbbaaa") == True
    assert is_accepted("bbabaa") == True
    assert is_accepted("bbaaba") == True
    assert is_accepted("bbaaab") == True
    assert is_accepted("babbaa") == True
    assert is_accepted("bababa") == True
    assert is_accepted("babaab") == True
    assert is_accepted("baabba") == True
    assert is_accepted("baabab") == True
    assert is_accepted("baaabb") == True
    assert is_accepted("abbbaa") == True
    assert is_accepted("abbaba") == True
    assert is_accepted("abbaab") == True
    assert is_accepted("ababba") == True
    assert is_accepted("ababab") == True
    assert is_accepted("abaabb") == True
    assert is_accepted("aabbba") == True
    assert is_accepted("aabbab") == True
    assert is_accepted("aababb") == True
    assert is_accepted("aaabbb") == True
    assert is_accepted("bbbbaa") == True
    assert is_accepted("bbbaba") == True
    assert is_accepted("bbbaab") == True
    assert is_accepted("bbabba") == True
    assert is_accepted("bbabab") == True
    assert is_accepted("bbaabb") == True
    assert is_accepted("babbba") == True
    assert is_accepted("babbab") == True
    assert is_accepted("bababb") == True
    assert is_accepted("baabbb") == True
    assert is_accepted("abbbba") == True
    assert is_accepted("abbbab") == True
    assert is_accepted("abbabb") == True
    assert is_accepted("ababbb") == True
    assert is_accepted("aabbbb") == True
    assert is_accepted("bbbbba") == True
    assert is_accepted("bbbbab") == True
    assert is_accepted("bbbabb") == True
    assert is_accepted("bbabbb") == True
    assert is_accepted("babbbb") == True
    assert is_accepted("abbbbb") == True
    assert is_accepted("bbbbbb") == False